"use client";

import { useEffect, useMemo, useState } from "react";

function Panel({ children, className="" }) { return <div className={`rounded-[28px] border border-white/10 bg-gradient-to-b from-slate-900/85 to-slate-950/80 ${className}`}>{children}</div>; }

export default function CommissionerReportsHub({ league, data, sourceLabel, printSeasonReport }) {
  const [tab,setTab]=useState("announcements"); const [message,setMessage]=useState("");
  const snapshotKey=`commissioner-snapshots:v1:${league.league_id}`; const [snapshots,setSnapshots]=useState([]);
  useEffect(()=>{try{setSnapshots(JSON.parse(localStorage.getItem(snapshotKey)||"[]"));}catch{}},[snapshotKey]);
  const standings=useMemo(()=>[...data.managers].sort((a,b)=>b.wins-a.wins||b.points-a.points),[data.managers]);
  const weekly=useMemo(()=>{const leader=standings[0];const active=[...data.managers].sort((a,b)=>b.transactions-a.transactions)[0];return `${league.name} Weekly Commissioner Digest\n\n${leader?`${leader.name} leads at ${leader.wins}-${leader.losses} with ${leader.points.toFixed(1)} points.`:"Standings are not yet available."}\n${active?`${active.name} leads activity with ${active.transactions} recorded moves.`:""}\nLeague health: ${Math.round(data.healthScore)}/100. Balance: ${Math.round(data.balanceScore)}/100. Participation: ${Math.round(data.participation*100)}%.\n${data.attentionCount?`${data.attentionCount} private review item(s) remain available to the commissioner.`:"No dashboard review items currently require attention."}\n\nPlease review league deadlines and contact the commissioner with questions.`;},[data,league,standings]);
  const publicReport=`${league.name} Public League Report\nHealth: ${Math.round(data.healthScore)}/100\nBalance: ${Math.round(data.balanceScore)}/100\nParticipation: ${Math.round(data.participation*100)}%\nOpen rosters: ${data.managers.filter((manager)=>manager.orphan).length}\nValuation source: ${sourceLabel}\n\nPrivate notes, dues, cases, and manager warnings are excluded.`;
  const privateReport=`${publicReport}\n\nPRIVATE COMMISSIONER SECTION\nReview items: ${data.attentionCount}\n${data.managers.flatMap((manager)=>manager.reviewSignals.map((signal)=>`- ${manager.ownerName||manager.name}: ${signal.label}`)).join("\n")||"No manager signals."}`;
  const copy=async(text,label)=>{try{await navigator.clipboard.writeText(text);setMessage(`${label} copied.`);}catch{setMessage(`${label} could not be copied.`);}};
  const saveSnapshot=()=>{const next=[{id:Date.now(),date:new Date().toISOString(),health:Math.round(data.healthScore),balance:Math.round(data.balanceScore),participation:Math.round(data.participation*100),review:data.attentionCount,open:data.managers.filter((manager)=>manager.orphan).length,source:sourceLabel},...snapshots].slice(0,24);setSnapshots(next);localStorage.setItem(snapshotKey,JSON.stringify(next));setMessage("Audit snapshot saved.");};
  return <div className="mt-6 space-y-5"><Panel className="overflow-hidden"><div className="border-b border-white/10 bg-[radial-gradient(circle_at_90%_0%,rgba(139,92,246,.18),transparent_40%)] p-5 sm:p-6"><div className="text-[11px] font-semibold uppercase tracking-[.24em] text-violet-200/55">Reports and communications</div><h2 className="mt-1 text-2xl font-black sm:text-3xl">One publishing center</h2><p className="mt-2 text-sm text-white/45">Announcements, audience-safe reports, printable season reports, and audit snapshots.</p></div><div className="flex overflow-x-auto p-2">{[["announcements","Announcements"],["reports","Public & Private"],["pdf","Season PDF"],["timeline","Audit Timeline"]].map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===key?"bg-white/10 text-white":"text-white/42"}`}>{label}</button>)}</div></Panel>
    {tab==="announcements"?<Panel className="p-5"><h3 className="text-xl font-black">Weekly commissioner digest</h3><textarea readOnly value={weekly} rows={12} className="mt-4 w-full rounded-2xl border border-white/10 bg-slate-950 p-3 text-sm leading-6 text-white/60"/><button onClick={()=>copy(weekly,"Weekly digest")} className="mt-3 rounded-xl bg-violet-300/[0.08] px-4 py-2 text-sm font-semibold text-violet-100">Copy digest</button></Panel>:null}
    {tab==="reports"?<div className="grid gap-5 lg:grid-cols-2"><Panel className="p-5"><div className="text-[11px] uppercase tracking-wider text-emerald-200/50">Public</div><h3 className="mt-1 text-xl font-black">Sanitized league report</h3><pre className="mt-4 whitespace-pre-wrap rounded-2xl border border-white/10 bg-slate-950 p-3 text-xs leading-5 text-white/55">{publicReport}</pre><button onClick={()=>copy(publicReport,"Public report")} className="mt-3 rounded-xl bg-emerald-300/[0.07] px-4 py-2 text-sm font-semibold text-emerald-100">Copy public report</button></Panel><Panel className="p-5"><div className="text-[11px] uppercase tracking-wider text-amber-200/50">Private</div><h3 className="mt-1 text-xl font-black">Commissioner-only report</h3><pre className="mt-4 whitespace-pre-wrap rounded-2xl border border-white/10 bg-slate-950 p-3 text-xs leading-5 text-white/55">{privateReport}</pre><button onClick={()=>copy(privateReport,"Private report")} className="mt-3 rounded-xl bg-amber-300/[0.07] px-4 py-2 text-sm font-semibold text-amber-100">Copy private report</button></Panel></div>:null}
    {tab==="pdf"?<Panel className="p-6"><h3 className="text-2xl font-black">Full season commissioner report</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-white/42">Standings, participation, recognitions, settings identity, review context, and recommendations. On mobile, the report opens with a manual Print / Save as PDF control.</p><button onClick={printSeasonReport} className="mt-5 rounded-xl bg-cyan-300/[0.09] px-5 py-3 text-sm font-semibold text-cyan-100">Open full season report</button></Panel>:null}
    {tab==="timeline"?<Panel className="p-5"><div className="flex items-end justify-between"><div><h3 className="text-xl font-black">Audit timeline</h3><p className="mt-1 text-xs text-white/38">Saved baselines and historical Sleeper seasons remain separate: this timeline tracks commissioner snapshots.</p></div><button onClick={saveSnapshot} className="rounded-xl bg-emerald-300/[0.08] px-4 py-2 text-sm font-semibold text-emerald-100">Save snapshot</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="text-left text-xs text-white/35"><tr><th className="p-3">Date</th><th className="p-3">Health</th><th className="p-3">Balance</th><th className="p-3">Participation</th><th className="p-3">Review</th><th className="p-3">Open</th><th className="p-3">Source</th></tr></thead><tbody>{snapshots.map((row)=><tr key={row.id} className="border-t border-white/[0.06]"><td className="p-3">{new Date(row.date).toLocaleDateString()}</td><td className="p-3">{row.health}/100</td><td className="p-3">{row.balance}/100</td><td className="p-3">{row.participation}%</td><td className="p-3">{row.review}</td><td className="p-3">{row.open}</td><td className="p-3">{row.source||"—"}</td></tr>)}</tbody></table>{!snapshots.length?<div className="p-6 text-center text-sm text-white/35">No snapshots saved.</div>:null}</div></Panel>:null}
    {message?<div className="rounded-2xl border border-cyan-300/12 bg-cyan-300/[0.05] p-3 text-sm text-cyan-100">{message}</div>:null}
  </div>;
}
