"use client";

import { useEffect, useRef, useState } from "react";

function Panel({ children, className = "" }) { return <div className={`rounded-[28px] border border-white/10 bg-gradient-to-b from-slate-900/85 to-slate-950/80 ${className}`}>{children}</div>; }
function fieldClass() { return "w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-cyan-300/30"; }

export default function CommissionerAdminHub({ league, data }) {
  const [tab,setTab]=useState("dues");
  const operationsKey=`commissioner-operations:v1:${league.league_id}`;
  const governanceKey=`commissioner-governance:v1:${league.league_id}`;
  const draftKey=`commissioner-draft-ready:v1:${league.league_id}`;
  const [operations,setOperations]=useState({actions:{},dues:{},deadlines:[],constitution:""});
  const [governance,setGovernance]=useState({incidents:[],playoffRules:"",template:"custom"});
  const [draftChecks,setDraftChecks]=useState({});
  const [drafts,setDrafts]=useState(null); const [draftLoading,setDraftLoading]=useState(false);
  const [message,setMessage]=useState(""); const fileRef=useRef(null);
  useEffect(()=>{try{setOperations({actions:{},dues:{},deadlines:[],constitution:"",...JSON.parse(localStorage.getItem(operationsKey)||"{}")});setGovernance({incidents:[],playoffRules:"",template:"custom",...JSON.parse(localStorage.getItem(governanceKey)||"{}")});setDraftChecks(JSON.parse(localStorage.getItem(draftKey)||"{}"));}catch{}},[operationsKey,governanceKey,draftKey]);
  const saveOperations=(next)=>{setOperations(next);try{localStorage.setItem(operationsKey,JSON.stringify(next));}catch{}};
  const saveGovernance=(next)=>{setGovernance(next);try{localStorage.setItem(governanceKey,JSON.stringify(next));}catch{}};
  const saveDraft=(next)=>{setDraftChecks(next);try{localStorage.setItem(draftKey,JSON.stringify(next));}catch{}};
  const updateDues=(id,patch)=>saveOperations({...operations,dues:{...operations.dues,[id]:{...(operations.dues[id]||{}),...patch}}});
  const updateDeadline=(id,patch)=>saveOperations({...operations,deadlines:operations.deadlines.map((row)=>row.id===id?{...row,...patch}:row)});
  const updateIncident=(id,patch)=>saveGovernance({...governance,incidents:governance.incidents.map((row)=>row.id===id?{...row,...patch}:row)});
  const slots=(league.roster_positions||[]).map((slot)=>String(slot).toUpperCase());
  const constitutionChecks=[[/super\s*flex|sf\b/i,slots.includes("SUPER_FLEX"),"Superflex"],[/median/i,!!Number(league?.settings?.league_average_match),"Median game"],[/taxi/i,slots.some((slot)=>slot.includes("TAXI"))||Number(league?.settings?.taxi_slots)>0,"Taxi squad"],[/\bir\b|injured reserve/i,slots.some((slot)=>slot==="IR"||slot.includes("RESERVE"))||Number(league?.settings?.reserve_slots)>0,"IR / reserve"],[/trade deadline/i,Number(league?.settings?.trade_deadline)>0,"Trade deadline"],[/playoff/i,Number(league?.settings?.playoff_teams)>0,"Playoff field"]].filter(([pattern])=>pattern.test(operations.constitution));
  const checklist=["Dues and deposits confirmed","Every franchise has a committed manager","Draft order reviewed and published","Traded picks verified","Keepers or cuts finalized","Draft rules and timer announced"];
  const loadDrafts=async()=>{setDraftLoading(true);try{const response=await fetch(`https://api.sleeper.app/v1/league/${league.league_id}/drafts`,{cache:"no-store"});setDrafts(response.ok?await response.json():[]);}catch{setDrafts([]);}finally{setDraftLoading(false);}};
  const templates={dynasty:"Annual rookie draft, future-pick trading, taxi rules, trade deadline, playoff seeding, and multi-year dues.",redraft:"Annual roster reset, waiver rules, trade deadline, playoff seeding, and season-only dues.",bestball:"Automatic optimal scoring, draft rules, roster limits, waivers if enabled, and playoff format.",custom:""};
  const exportBackup=()=>{const payload={};for(let index=0;index<localStorage.length;index+=1){const key=localStorage.key(index);if(key?.startsWith("commissioner-")||key?.startsWith("orphan-recruiting:"))payload[key]=localStorage.getItem(key);}const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),payload},null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`fantasy-arsenal-admin-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage("Backup downloaded.");};
  const restore=async(file)=>{try{const parsed=JSON.parse(await file.text());if(!parsed?.payload)throw new Error();Object.entries(parsed.payload).forEach(([key,value])=>{if(key.startsWith("commissioner-")||key.startsWith("orphan-recruiting:"))localStorage.setItem(key,String(value));});setMessage("Backup restored. Refresh to load all records.");}catch{setMessage("Invalid commissioner backup file.");}};
  return <div className="mt-6 space-y-5"><Panel className="overflow-hidden"><div className="border-b border-white/10 bg-[radial-gradient(circle_at_90%_0%,rgba(245,158,11,.16),transparent_40%)] p-5 sm:p-6"><div className="text-[11px] font-semibold uppercase tracking-[.24em] text-amber-200/55">League administration</div><h2 className="mt-1 text-2xl font-black sm:text-3xl">One private league office</h2><p className="mt-2 text-sm text-white/45">Payments, deadlines, rules, cases, draft readiness, templates, and workspace protection. Local-only and never written to Sleeper.</p></div><div className="overflow-x-auto p-2"><div className="flex w-max gap-1">{[["dues","Dues & Renewal"],["deadlines","Deadlines"],["constitution","Rules"],["incidents","Cases"],["draft","Draft Ready"],["templates","Templates"],["backup","Backup"]].map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===key?"bg-white/10 text-white":"text-white/42"}`}>{label}</button>)}</div></div></Panel>
    {tab==="dues"?<Panel className="overflow-hidden"><div className="border-b border-white/10 p-5"><h3 className="text-xl font-black">Dues, deposits, and renewal</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-left text-xs text-white/35"><tr><th className="p-3">Manager</th><th className="p-3">Renewal</th><th className="p-3">Dues</th><th className="p-3">Deposit</th><th className="p-3">Private note</th></tr></thead><tbody>{data.managers.map((manager)=>{const row=operations.dues[manager.rosterId]||{};return <tr key={manager.rosterId} className="border-t border-white/[0.06]"><td className="p-3 font-semibold">{manager.ownerName||manager.name}</td><td className="p-3"><select value={row.renewal||"unknown"} onChange={(event)=>updateDues(manager.rosterId,{renewal:event.target.value})} className={fieldClass()}><option value="unknown">Unknown</option><option value="returning">Returning</option><option value="undecided">Undecided</option><option value="leaving">Leaving</option></select></td><td className="p-3"><select value={row.dues||"untracked"} onChange={(event)=>updateDues(manager.rosterId,{dues:event.target.value})} className={fieldClass()}><option value="untracked">Untracked</option><option value="paid">Paid</option><option value="partial">Partial</option><option value="due">Due</option></select></td><td className="p-3"><input value={row.deposit||""} onChange={(event)=>updateDues(manager.rosterId,{deposit:event.target.value})} placeholder="$ / status" className={fieldClass()} /></td><td className="p-3"><input value={row.note||""} onChange={(event)=>updateDues(manager.rosterId,{note:event.target.value})} placeholder="Private note" className={fieldClass()} /></td></tr>;})}</tbody></table></div></Panel>:null}
    {tab==="deadlines"?<Panel className="p-5"><div className="flex items-end justify-between"><div><h3 className="text-xl font-black">League calendar</h3><p className="mt-1 text-xs text-white/38">Sleeper deadline plus private commissioner dates.</p></div><button onClick={()=>saveOperations({...operations,deadlines:[...operations.deadlines,{id:String(Date.now()),title:"New deadline",date:"",complete:false}]})} className="rounded-xl bg-cyan-300/[0.08] px-3 py-2 text-xs font-semibold text-cyan-100">Add deadline</button></div>{Number(league?.settings?.trade_deadline)?<div className="mt-4 rounded-2xl border border-violet-300/10 bg-violet-300/[0.04] p-3 text-sm">Sleeper trade deadline · Week {league.settings.trade_deadline}</div>:null}<div className="mt-3 space-y-2">{operations.deadlines.map((row)=><div key={row.id} className="grid gap-2 rounded-2xl border border-white/10 p-3 sm:grid-cols-[auto_1fr_170px_auto]"><input type="checkbox" checked={row.complete} onChange={(event)=>updateDeadline(row.id,{complete:event.target.checked})}/><input value={row.title} onChange={(event)=>updateDeadline(row.id,{title:event.target.value})} className={fieldClass()}/><input type="date" value={row.date} onChange={(event)=>updateDeadline(row.id,{date:event.target.value})} className={fieldClass()}/><button onClick={()=>saveOperations({...operations,deadlines:operations.deadlines.filter((item)=>item.id!==row.id)})} className="text-xs text-rose-100/60">Remove</button></div>)}</div></Panel>:null}
    {tab==="constitution"?<div className="grid gap-5 lg:grid-cols-2"><Panel className="p-5"><h3 className="text-xl font-black">Constitution workspace</h3><textarea value={operations.constitution} onChange={(event)=>saveOperations({...operations,constitution:event.target.value})} rows={16} placeholder="Paste league rules here…" className={`${fieldClass()} mt-4`} /></Panel><Panel className="p-5"><h3 className="text-xl font-black">Observable alignment</h3><div className="mt-4 space-y-2">{constitutionChecks.length?constitutionChecks.map(([,aligned,label])=><div key={label} className={`rounded-2xl border p-3 ${aligned?"border-emerald-300/12 bg-emerald-300/[0.04]":"border-amber-300/12 bg-amber-300/[0.04]"}`}><div className="flex justify-between"><span className="font-semibold">{label}</span><span className="text-[10px] uppercase">{aligned?"Aligned":"Review"}</span></div></div>):<div className="text-sm text-white/38">Paste rules to compare detectable settings.</div>}</div><label className="mt-5 block text-xs text-white/45">Custom playoff and tiebreaker rules<textarea value={governance.playoffRules} onChange={(event)=>saveGovernance({...governance,playoffRules:event.target.value})} rows={6} className={`${fieldClass()} mt-1.5`} /></label></Panel></div>:null}
    {tab==="incidents"?<Panel className="overflow-hidden"><div className="flex items-end justify-between border-b border-white/10 p-5"><div><h3 className="text-xl font-black">Incident and dispute log</h3><p className="mt-1 text-xs text-white/38">Private case records.</p></div><button onClick={()=>saveGovernance({...governance,incidents:[{id:Date.now(),title:"New case",status:"Open",manager:"",evidence:"",resolution:""},...governance.incidents]})} className="rounded-xl bg-rose-300/[0.07] px-3 py-2 text-xs font-semibold text-rose-100">New case</button></div><div className="divide-y divide-white/[0.06]">{governance.incidents.map((row)=><details key={row.id} className="p-4"><summary className="cursor-pointer font-semibold">{row.title} <span className="text-xs font-normal text-white/35">· {row.status}</span></summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={row.title} onChange={(event)=>updateIncident(row.id,{title:event.target.value})} className={fieldClass()}/><select value={row.status} onChange={(event)=>updateIncident(row.id,{status:event.target.value})} className={fieldClass()}><option>Open</option><option>Reviewing</option><option>Resolved</option><option>Dismissed</option></select><select value={row.manager} onChange={(event)=>updateIncident(row.id,{manager:event.target.value})} className={fieldClass()}><option value="">No manager</option>{data.managers.map((manager)=><option key={manager.rosterId}>{manager.ownerName||manager.name}</option>)}</select><button onClick={()=>saveGovernance({...governance,incidents:governance.incidents.filter((item)=>item.id!==row.id)})} className="text-left text-xs text-rose-100/60">Delete</button><textarea value={row.evidence} onChange={(event)=>updateIncident(row.id,{evidence:event.target.value})} rows={3} placeholder="Evidence…" className={fieldClass()}/><textarea value={row.resolution} onChange={(event)=>updateIncident(row.id,{resolution:event.target.value})} rows={3} placeholder="Resolution…" className={fieldClass()}/></div></details>)}{!governance.incidents.length?<div className="p-8 text-center text-sm text-white/35">No cases recorded.</div>:null}</div></Panel>:null}
    {tab==="draft"?<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><Panel className="p-5"><h3 className="text-xl font-black">Draft readiness</h3><div className="mt-4 space-y-2">{checklist.map((label,index)=><button key={label} onClick={()=>saveDraft({...draftChecks,[index]:!draftChecks[index]})} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${draftChecks[index]?"border-emerald-300/15 bg-emerald-300/[0.04]":"border-white/10"}`}><span className="grid h-6 w-6 place-items-center rounded-lg bg-white/[0.05]">{draftChecks[index]?"✓":""}</span><span className="text-sm font-semibold">{label}</span></button>)}</div></Panel><Panel className="p-5"><div className="flex justify-between"><h3 className="font-black">Sleeper draft state</h3><button onClick={loadDrafts} className="text-xs text-cyan-100/65">{draftLoading?"Loading…":"Refresh"}</button></div>{drafts?<div className="mt-4 space-y-2">{drafts.map((draft)=><div key={draft.draft_id} className="rounded-2xl border border-white/10 p-3"><div className="font-semibold">{draft.season} · {draft.status}</div><div className="text-xs text-white/35">{draft.settings?.rounds||"—"} rounds</div></div>)}</div>:<button onClick={loadDrafts} className="mt-4 w-full rounded-2xl border border-white/10 p-4 text-sm text-white/45">Load drafts</button>}</Panel></div>:null}
    {tab==="templates"?<Panel className="p-5"><h3 className="text-xl font-black">League operating templates</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(templates).map(([key,text])=><button key={key} onClick={()=>saveGovernance({...governance,template:key,playoffRules:governance.playoffRules||text})} className={`rounded-2xl border p-4 text-left capitalize ${governance.template===key?"border-cyan-300/20 bg-cyan-300/[0.06]":"border-white/10"}`}><div className="font-semibold">{key}</div><div className="mt-2 text-xs normal-case leading-5 text-white/38">{text||"Blank custom template."}</div></button>)}</div></Panel>:null}
    {tab==="backup"?<Panel className="p-5"><h3 className="text-xl font-black">Commissioner workspace backup</h3><p className="mt-2 text-sm text-white/42">Protects local dues, deadlines, cases, notes, reviews, snapshots, and orphan recruiting fields.</p><div className="mt-4 flex gap-2"><button onClick={exportBackup} className="rounded-xl bg-cyan-300/[0.08] px-4 py-2 text-sm font-semibold text-cyan-100">Download backup</button><button onClick={()=>fileRef.current?.click()} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white/60">Restore</button><input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={(event)=>event.target.files?.[0]&&restore(event.target.files[0])}/></div>{message?<div className="mt-4 text-sm text-cyan-100">{message}</div>:null}</Panel>:null}
  </div>;
}
