name = "tfa-draft-registry"
main = "index.js"
compatibility_date = "2026-02-22"

[[durable_objects.bindings]]
name = "DRAFT_REGISTRY"
class_name = "DraftRegistry"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DraftRegistry"]

[[d1_databases]]
binding = "PUSH_DB"
database_name = "tfa_push"
database_id = "9999634a-7da3-4ffe-a641-c6fa9dd9450a"