"use client";

import { useEffect,useMemo,useState } from "react";
import Navbar from "../../components/Navbar";
import BackgroundParticles from "../../components/BackgroundParticles";
import AvatarImage from "../../components/AvatarImage";
import { useSleeper } from "../../context/SleeperContext";

const num=value=>Number(value||0);const getJson=async url=>{const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error();return response.json();};
async function concurrentMap(rows,limit,worker,onProgress){const results=new Array(rows.length);let cursor=0,done=0;await Promise.all(Array.from({length:Math.min(limit,rows.length)},async()=>{while(cursor<rows.length){const index=cursor++;results[index]=await worker(rows[index],index);done++;onProgress?.(done,rows.length);}}));return results;}
function Panel({children,className=""}){return <div className={`rounded-[28px] border border-white/10 bg-gradient-to-b from-slate-900/90 to-slate-950/85 ${className}`}>{children}</div>;}
function Stat({label,value,detail}){return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-3"><div className="text-[9px] font-semibold uppercase tracking-[.16em] text-white/35">{label}</div><div className="mt-1 text-xl font-black">{value}</div>{detail?<div className="mt-1 text-[10px] text-white/32">{detail}</div>:null}</div>;}
const playerName=(players,id)=>players?.[id]?.full_name||players?.[id]?.search_full_name||id;
export default function GameCenterClient(){
 const {username,year,leagues,players}=useSleeper();const [week,setWeek]=useState(1);const [rows,setRows]=useState([]);const [games,setGames]=useState([]);const [loading,setLoading]=useState(false);const [progress,setProgress]=useState("");const [tab,setTab]=useState("spotlight");const [query,setQuery]=useState("");const [error,setError]=useState("");
 useEffect(()=>{getJson("https://api.sleeper.app/v1/state/nfl").then(state=>setWeek(Math.max(1,num(state.week)||1))).catch(()=>{});},[]);
 const scan=async()=>{if(!username)return;setLoading(true);setError("");setRows([]);try{const root=await getJson(`https://api.sleeper.app/v1/user/${encodeURIComponent(username)}`);const scanned=await concurrentMap(leagues||[],10,async league=>{try{const [rosters,users,matchups]=await Promise.all([league.rosters?Promise.resolve(league.rosters):getJson(`https://api.sleeper.app/v1/league/${league.league_id}/rosters`),league.users?Promise.resolve(league.users):getJson(`https://api.sleeper.app/v1/league/${league.league_id}/users`),getJson(`https://api.sleeper.app/v1/league/${league.league_id}/matchups/${week}`)]);const mine=rosters.find(roster=>String(roster.owner_id)===String(root.user_id));if(!mine)return null;const myMatch=matchups.find(row=>String(row.roster_id)===String(mine.roster_id));if(!myMatch)return null;const opponentMatch=matchups.find(row=>row.matchup_id===myMatch.matchup_id&&String(row.roster_id)!==String(mine.roster_id));const opponentRoster=rosters.find(roster=>String(roster.roster_id)===String(opponentMatch?.roster_id));const opponentUser=users.find(user=>String(user.user_id)===String(opponentRoster?.owner_id));return{league,mine,myMatch,opponentMatch,opponentRoster,opponentName:opponentUser?.metadata?.team_name||opponentUser?.display_name||opponentUser?.username||"Opponent"};}catch{return null;}},(done,total)=>setProgress(`Scanning lineups ${done}/${total}`));setRows(scanned.filter(Boolean));const schedule=await getJson(`/api/nfl-scoreboard?season=${year||new Date().getFullYear()}&week=${week}`).catch(()=>({games:[]}));setGames(schedule.games||[]);}catch{setError("The cross-league scan could not be completed.");}finally{setLoading(false);setProgress("");}};
 useEffect(()=>{if(username&&(leagues||[]).length)scan();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[username,week]);
 const gameByTeam=useMemo(()=>{const map=new Map();games.forEach(game=>game.teams.forEach(team=>map.set(team,game)));return map;},[games]);
 const playerRows=useMemo(()=>{const map=new Map();rows.forEach(row=>{const myStarters=new Set((row.myMatch.starters||[]).map(String));const oppStarters=new Set((row.opponentMatch?.starters||[]).map(String));myStarters.forEach(id=>{if(!id||id==="0")return;const current=map.get(id)||{id,for:[],against:[],points:[]};current.for.push({league:row.league.name,points:num(row.myMatch.players_points?.[id])});current.points.push(num(row.myMatch.players_points?.[id]));map.set(id,current);});oppStarters.forEach(id=>{if(!id||id==="0")return;const current=map.get(id)||{id,for:[],against:[],points:[]};current.against.push({league:row.league.name,opponent:row.opponentName,points:num(row.opponentMatch?.players_points?.[id])});current.points.push(num(row.opponentMatch?.players_points?.[id]));map.set(id,current);});});return[...map.values()].map(row=>{const player=players?.[row.id];const game=gameByTeam.get(player?.team);return{...row,player,name:playerName(players,row.id),conflict:row.for.length>0&&row.against.length>0,game,points:row.points.length?Math.max(...row.points):0};}).sort((a,b)=>(a.game?.date||"9999").localeCompare(b.game?.date||"9999")||b.conflict-a.conflict||b.for.length+b.against.length-(a.for.length+a.against.length));},[gameByTeam,players,rows]);
 const filtered=playerRows.filter(row=>!query.trim()||`${row.name} ${row.player?.team} ${row.player?.position}`.toLowerCase().includes(query.toLowerCase()));const conflicts=playerRows.filter(row=>row.conflict);const roots=playerRows.filter(row=>row.for.length&&!row.against.length);const boos=playerRows.filter(row=>row.against.length&&!row.for.length);
 const scoreboards=rows.map(row=>({league:row.league.name,mine:num(row.myMatch.points),opponent:num(row.opponentMatch?.points),opponentName:row.opponentName,matchupId:row.myMatch.matchup_id})).sort((a,b)=>Math.abs(a.mine-a.opponent)-Math.abs(b.mine-b.opponent));
 return <main className="min-h-screen text-white"><BackgroundParticles/><Navbar pageTitle="Game Center"/><div className="mx-auto max-w-7xl px-4 pb-20 pt-20"><header className="rounded-[34px] border border-emerald-300/15 bg-[radial-gradient(circle_at_88%_0%,rgba(16,185,129,.2),transparent_36%),radial-gradient(circle_at_8%_100%,rgba(34,211,238,.13),transparent_34%),linear-gradient(145deg,rgba(15,23,42,.98),rgba(2,6,23,.96))] p-5 sm:p-7"><div className="text-[11px] font-semibold uppercase tracking-[.28em] text-emerald-200/60">Cross-league Sunday command</div><h1 className="mt-2 text-3xl font-black sm:text-5xl">Fantasy Game Center</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/52">Every root, boo, conflict, kickoff, fantasy point, and league score—organized across your Sleeper portfolio.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><select value={week} onChange={event=>setWeek(num(event.target.value))} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3"><option disabled>Week</option>{Array.from({length:18},(_,index)=>index+1).map(value=><option key={value}> {value}</option>)}</select><button onClick={scan} disabled={loading} className="rounded-2xl bg-emerald-300/10 px-5 py-3 font-bold text-emerald-100">{loading?progress||"Scanning…":"Refresh all leagues"}</button></div></header>{error?<div className="mt-5 rounded-2xl border border-rose-300/15 bg-rose-300/[0.07] p-4 text-sm text-rose-100">{error}</div>:null}{!username?<Panel className="mt-5 p-8 text-center text-white/50">Log in on the homepage to build your cross-league game center.</Panel>:null}{username?<><section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6"><Stat label="Leagues active" value={rows.length}/><Stat label="Players for you" value={playerRows.filter(row=>row.for.length).length}/><Stat label="Against you" value={playerRows.filter(row=>row.against.length).length}/><Stat label="Conflicts" value={conflicts.length}/><Stat label="Strong roots" value={roots.filter(row=>row.for.length>=2).length}/><Stat label="Strong boos" value={boos.filter(row=>row.against.length>=2).length}/></section><Panel className="sticky top-14 z-30 mt-5 overflow-x-auto rounded-2xl bg-slate-950/95 p-2"><div className="flex w-max gap-1">{[["spotlight","Spotlight"],["schedule","Player Schedule"],["scores","League Scores"]].map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===key?"bg-white/10":"text-white/42"}`}>{label}</button>)}</div></Panel>
 {tab==="spotlight"?<div className="mt-5 grid gap-5 lg:grid-cols-3">{[["Conflicts",conflicts,"border-amber-300/15","⚔"],["Strong roots",roots,"border-emerald-300/15","⚡"],["Strong boos",boos,"border-rose-300/15","↓"]].map(([title,list,tone,icon])=><Panel key={title} className={`overflow-hidden ${tone}`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black">{icon} {title}</h2></div><div className="divide-y divide-white/[0.06]">{list.slice(0,15).map(row=><details key={row.id} className="p-3"><summary className="flex cursor-pointer list-none items-center gap-3"><AvatarImage name={row.name} playerId={row.id} size={38} className="rounded-xl" alt=""/><div className="min-w-0 flex-1"><div className="truncate font-semibold">{row.name}</div><div className="text-xs text-white/32">{row.player?.position} · {row.player?.team||"FA"}</div></div><div className="text-right"><b>{row.points.toFixed(1)}</b><small className="block text-[9px] text-white/28">points</small></div></summary><div className="mt-3 pl-12 text-[11px] leading-5 text-white/40">For you: {row.for.map(item=>item.league).join(" · ")||"None"}<br/>Against: {row.against.map(item=>item.league).join(" · ")||"None"}</div></details>)}{!list.length?<div className="p-6 text-sm text-white/35">None this week.</div>:null}</div></Panel>)}</div>:null}
 {tab==="schedule"?<Panel className="mt-5 overflow-hidden"><div className="border-b border-white/10 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black">Player kickoff board</h2><p className="mt-1 text-xs text-white/35">Sorted by NFL kickoff. Points update with Sleeper matchup data.</p></div><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search player or team" className="rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm"/></div></div><div className="divide-y divide-white/[0.06]">{filtered.map(row=><details key={row.id} className="p-3 sm:p-4"><summary className="flex cursor-pointer list-none items-center gap-3"><div className={`grid h-9 w-9 place-items-center rounded-xl ${row.conflict?"bg-amber-300/10 text-amber-100":row.for.length?"bg-emerald-300/10 text-emerald-100":"bg-rose-300/10 text-rose-100"}`}>{row.conflict?"⚔":row.for.length?"⚡":"↓"}</div><AvatarImage name={row.name} playerId={row.id} size={42} className="rounded-xl" alt=""/><div className="min-w-0 flex-1"><div className="truncate font-semibold">{row.name}</div><div className="text-xs text-white/32">{row.player?.position} · {row.game?.date?new Date(row.game.date).toLocaleString([], {weekday:"short",hour:"numeric",minute:"2-digit"}):"Kickoff unavailable"} · {row.game?.status||""}</div></div><div className="text-right"><div className="text-lg font-black">{row.points.toFixed(1)}</div><div className="text-[9px] text-white/25">fantasy points</div></div></summary><div className="mt-3 grid gap-2 pl-12 text-xs sm:grid-cols-2"><div className="rounded-xl bg-emerald-300/[0.04] p-3"><b className="text-emerald-100">Starting for you ({row.for.length})</b><div className="mt-1 text-white/38">{row.for.map(item=>`${item.league} (${item.points.toFixed(1)})`).join(" · ")||"None"}</div></div><div className="rounded-xl bg-rose-300/[0.04] p-3"><b className="text-rose-100">Against you ({row.against.length})</b><div className="mt-1 text-white/38">{row.against.map(item=>`${item.league} (${item.points.toFixed(1)})`).join(" · ")||"None"}</div></div></div></details>)}</div></Panel>:null}
 {tab==="scores"?<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{scoreboards.map(row=>{const winning=row.mine>row.opponent;return <Panel key={row.league} className="p-4"><div className="truncate font-black">{row.league}</div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><div><div className={`text-2xl font-black ${winning?"text-emerald-100":""}`}>{row.mine.toFixed(1)}</div><div className="text-[10px] text-white/30">Your team</div></div><div className="text-xs text-white/20">VS</div><div><div className={`text-2xl font-black ${!winning&&row.opponent>row.mine?"text-rose-100":""}`}>{row.opponent.toFixed(1)}</div><div className="truncate text-[10px] text-white/30">{row.opponentName}</div></div></div><div className="mt-3 text-center text-[10px] text-white/32">{winning?`Ahead by ${(row.mine-row.opponent).toFixed(1)}`:row.mine===row.opponent?"Currently tied":`Behind by ${(row.opponent-row.mine).toFixed(1)}`}</div></Panel>})}</div>:null}</>:null}</div></main>;
}
